version: '3'
services:

  app0:
    image: nginx:latest
    container_name: 'app0'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
    restart: always
    environment:
      VIRTUAL_HOST: rehop.dev

networks:
  default:
    external:
      name: rd-shared

