version: '3'
services:

  proxy:
    image: nginx:latest
    container_name: proxy
    privileged: true
    volumes:
      - /etc/letsencrypt/live/rehop.dev-0001/fullchain.pem:/etc/nginx/certs/rehop.dev-0001/fullchain.pem:ro
      - /etc/letsencrypt/live/rehop.dev-0001/privkey.pem:/etc/nginx/certs/rehop.dev-0001/privkey.pem:ro    
      - ./html:/usr/share/nginx/html
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: always

networks:
  default:
    external:
      name: rd-shared



